package com.metafortech.calma.authentication.register.presentation

data class Country(
    val code: String,
    val dialCode: String,
    val name: String,
    val nameEn: String,
    val flagUrl: String
)

object CountryData {
    val countries = listOf<Country>(
        Country(
            "",
            "",
            "",
            "",
            "https://hatscripts.github.io/circle-flags/flags/xx.svg"),
        Country(
            "AE",
            "+971",
            "الإمارات العربية المتحدة",
            "United Arab Emirates",
            "https://hatscripts.github.io/circle-flags/flags/ae.svg"
        ),
        Country(
            "AF",
            "+93",
            "أفغانستان",
            "Afghanistan",
            "https://hatscripts.github.io/circle-flags/flags/af.svg"
        ),
        Country(
            "AL",
            "+355",
            "Shqipëria",
            "Albania",
            "https://hatscripts.github.io/circle-flags/flags/al.svg"
        ),
        Country(
            "AM",
            "+374",
            "Հայաստան",
            "Armenia",
            "https://hatscripts.github.io/circle-flags/flags/am.svg"
        ),
        Country(
            "AR",
            "+54",
            "Argentina",
            "Argentina",
            "https://hatscripts.github.io/circle-flags/flags/ar.svg"
        ),
        Country(
            "AT",
            "+43",
            "Österreich",
            "Austria",
            "https://hatscripts.github.io/circle-flags/flags/at.svg"
        ),
        Country(
            "AU",
            "+61",
            "Australia",
            "Australia",
            "https://hatscripts.github.io/circle-flags/flags/au.svg"
        ),
        Country(
            "AZ",
            "+994",
            "Azərbaycan",
            "Azerbaijan",
            "https://hatscripts.github.io/circle-flags/flags/az.svg"
        ),
        Country(
            "BA",
            "+387",
            "Bosna i Hercegovina",
            "Bosnia and Herzegovina",
            "https://hatscripts.github.io/circle-flags/flags/ba.svg"
        ),
        Country(
            "BD",
            "+880",
            "বাংলাদেশ",
            "Bangladesh",
            "https://hatscripts.github.io/circle-flags/flags/bd.svg"
        ),
        Country(
            "BE",
            "+32",
            "Belgique/België",
            "Belgium",
            "https://hatscripts.github.io/circle-flags/flags/be.svg"
        ),
        Country(
            "BG",
            "+359",
            "България",
            "Bulgaria",
            "https://hatscripts.github.io/circle-flags/flags/bg.svg"
        ),
        Country(
            "BH",
            "+973",
            "البحرين",
            "Bahrain",
            "https://hatscripts.github.io/circle-flags/flags/bh.svg"
        ),
        Country(
            "BR",
            "+55",
            "Brasil",
            "Brazil",
            "https://hatscripts.github.io/circle-flags/flags/br.svg"
        ),
        Country(
            "BT",
            "+975",
            "འབྲུག་ཡུལ",
            "Bhutan",
            "https://hatscripts.github.io/circle-flags/flags/bt.svg"
        ),
        Country(
            "BY",
            "+375",
            "Беларусь",
            "Belarus",
            "https://hatscripts.github.io/circle-flags/flags/by.svg"
        ),
        Country(
            "CA",
            "+1",
            "Canada",
            "Canada",
            "https://hatscripts.github.io/circle-flags/flags/ca.svg"
        ),
        Country(
            "CH",
            "+41",
            "Schweiz/Suisse/Svizzera",
            "Switzerland",
            "https://hatscripts.github.io/circle-flags/flags/ch.svg"
        ),
        Country(
            "CL",
            "+56",
            "Chile",
            "Chile",
            "https://hatscripts.github.io/circle-flags/flags/cl.svg"
        ),
        Country(
            "CN",
            "+86",
            "中国",
            "China",
            "https://hatscripts.github.io/circle-flags/flags/cn.svg"
        ),
        Country(
            "CO",
            "+57",
            "Colombia",
            "Colombia",
            "https://hatscripts.github.io/circle-flags/flags/co.svg"
        ),
        Country(
            "CZ",
            "+420",
            "Česko",
            "Czech Republic",
            "https://hatscripts.github.io/circle-flags/flags/cz.svg"
        ),
        Country(
            "DE",
            "+49",
            "Deutschland",
            "Germany",
            "https://hatscripts.github.io/circle-flags/flags/de.svg"
        ),
        Country(
            "DK",
            "+45",
            "Danmark",
            "Denmark",
            "https://hatscripts.github.io/circle-flags/flags/dk.svg"
        ),
        Country(
            "DZ",
            "+213",
            "الجزائر",
            "Algeria",
            "https://hatscripts.github.io/circle-flags/flags/dz.svg"
        ),
        Country(
            "EG",
            "+20",
            "مصر",
            "Egypt",
            "https://hatscripts.github.io/circle-flags/flags/eg.svg"
        ),
        Country(
            "ES",
            "+34",
            "España",
            "Spain",
            "https://hatscripts.github.io/circle-flags/flags/es.svg"
        ),
        Country(
            "FI",
            "+358",
            "Suomi",
            "Finland",
            "https://hatscripts.github.io/circle-flags/flags/fi.svg"
        ),
        Country(
            "FR",
            "+33",
            "France",
            "France",
            "https://hatscripts.github.io/circle-flags/flags/fr.svg"
        ),
        Country(
            "GB",
            "+44",
            "United Kingdom",
            "United Kingdom",
            "https://hatscripts.github.io/circle-flags/flags/gb.svg"
        ),
        Country(
            "GE",
            "+995",
            "საქართველო",
            "Georgia",
            "https://hatscripts.github.io/circle-flags/flags/ge.svg"
        ),
        Country(
            "GR",
            "+30",
            "Ελλάδα",
            "Greece",
            "https://hatscripts.github.io/circle-flags/flags/gr.svg"
        ),
        Country(
            "HR",
            "+385",
            "Hrvatska",
            "Croatia",
            "https://hatscripts.github.io/circle-flags/flags/hr.svg"
        ),
        Country(
            "HU",
            "+36",
            "Magyarország",
            "Hungary",
            "https://hatscripts.github.io/circle-flags/flags/hu.svg"
        ),
        Country(
            "ID",
            "+62",
            "Indonesia",
            "Indonesia",
            "https://hatscripts.github.io/circle-flags/flags/id.svg"
        ),
        Country(
            "IE",
            "+353",
            "Éire",
            "Ireland",
            "https://hatscripts.github.io/circle-flags/flags/ie.svg"
        ),
        Country(
            "IN",
            "+91",
            "भारत",
            "India",
            "https://hatscripts.github.io/circle-flags/flags/in.svg"
        ),
        Country(
            "IQ",
            "+964",
            "العراق",
            "Iraq",
            "https://hatscripts.github.io/circle-flags/flags/iq.svg"
        ),
        Country(
            "IR",
            "+98",
            "ایران",
            "Iran",
            "https://hatscripts.github.io/circle-flags/flags/ir.svg"
        ),
        Country(
            "IS",
            "+354",
            "Ísland",
            "Iceland",
            "https://hatscripts.github.io/circle-flags/flags/is.svg"
        ),
        Country(
            "IT",
            "+39",
            "Italia",
            "Italy",
            "https://hatscripts.github.io/circle-flags/flags/it.svg"
        ),
        Country(
            "JO",
            "+962",
            "الأردن",
            "Jordan",
            "https://hatscripts.github.io/circle-flags/flags/jo.svg"
        ),
        Country(
            "JP",
            "+81",
            "日本",
            "Japan",
            "https://hatscripts.github.io/circle-flags/flags/jp.svg"
        ),
        Country(
            "KE",
            "+254",
            "Kenya",
            "Kenya",
            "https://hatscripts.github.io/circle-flags/flags/ke.svg"
        ),
        Country(
            "KG",
            "+996",
            "Кыргызстан",
            "Kyrgyzstan",
            "https://hatscripts.github.io/circle-flags/flags/kg.svg"
        ),
        Country(
            "KH",
            "+855",
            "កម្ពុជា",
            "Cambodia",
            "https://hatscripts.github.io/circle-flags/flags/kh.svg"
        ),
        Country(
            "KR",
            "+82",
            "대한민국",
            "South Korea",
            "https://hatscripts.github.io/circle-flags/flags/kr.svg"
        ),
        Country(
            "KW",
            "+965",
            "الكويت",
            "Kuwait",
            "https://hatscripts.github.io/circle-flags/flags/kw.svg"
        ),
        Country(
            "KZ",
            "+7",
            "Қазақстан",
            "Kazakhstan",
            "https://hatscripts.github.io/circle-flags/flags/kz.svg"
        ),
        Country(
            "LB",
            "+961",
            "لبنان",
            "Lebanon",
            "https://hatscripts.github.io/circle-flags/flags/lb.svg"
        ),
        Country(
            "LK",
            "+94",
            "ශ්‍රී ලංකාව",
            "Sri Lanka",
            "https://hatscripts.github.io/circle-flags/flags/lk.svg"
        ),
        Country(
            "LY",
            "+218",
            "ليبيا",
            "Libya",
            "https://hatscripts.github.io/circle-flags/flags/ly.svg"
        ),
        Country(
            "MA",
            "+212",
            "المغرب",
            "Morocco",
            "https://hatscripts.github.io/circle-flags/flags/ma.svg"
        ),
        Country(
            "MC",
            "+377",
            "Monaco",
            "Monaco",
            "https://hatscripts.github.io/circle-flags/flags/mc.svg"
        ),
        Country(
            "MD",
            "+373",
            "Moldova",
            "Moldova",
            "https://hatscripts.github.io/circle-flags/flags/md.svg"
        ),
        Country(
            "ME",
            "+382",
            "Crna Gora",
            "Montenegro",
            "https://hatscripts.github.io/circle-flags/flags/me.svg"
        ),
        Country(
            "MK",
            "+389",
            "Северна Македонија",
            "North Macedonia",
            "https://hatscripts.github.io/circle-flags/flags/mk.svg"
        ),
        Country(
            "ML",
            "+223",
            "Mali",
            "Mali",
            "https://hatscripts.github.io/circle-flags/flags/ml.svg"
        ),
        Country(
            "MM",
            "+95",
            "မြန်မာ",
            "Myanmar",
            "https://hatscripts.github.io/circle-flags/flags/mm.svg"
        ),
        Country(
            "MN",
            "+976",
            "Монгол улс",
            "Mongolia",
            "https://hatscripts.github.io/circle-flags/flags/mn.svg"
        ),
        Country(
            "MO",
            "+853",
            "澳門",
            "Macau",
            "https://hatscripts.github.io/circle-flags/flags/mo.svg"
        ),
        Country(
            "MR",
            "+222",
            "موريتانيا",
            "Mauritania",
            "https://hatscripts.github.io/circle-flags/flags/mr.svg"
        ),
        Country(
            "MT",
            "+356",
            "Malta",
            "Malta",
            "https://hatscripts.github.io/circle-flags/flags/mt.svg"
        ),
        Country(
            "MU",
            "+230",
            "Maurice",
            "Mauritius",
            "https://hatscripts.github.io/circle-flags/flags/mu.svg"
        ),
        Country(
            "MX",
            "+52",
            "México",
            "Mexico",
            "https://hatscripts.github.io/circle-flags/flags/mx.svg"
        ),
        Country(
            "MY",
            "+60",
            "Malaysia",
            "Malaysia",
            "https://hatscripts.github.io/circle-flags/flags/my.svg"
        ),
        Country(
            "MZ",
            "+258",
            "Moçambique",
            "Mozambique",
            "https://hatscripts.github.io/circle-flags/flags/mz.svg"
        ),
        Country(
            "NA",
            "+264",
            "Namibia",
            "Namibia",
            "https://hatscripts.github.io/circle-flags/flags/na.svg"
        ),
        Country(
            "NE",
            "+227",
            "النيجر",
            "Niger",
            "https://hatscripts.github.io/circle-flags/flags/ne.svg"
        ),
        Country(
            "NG",
            "+234",
            "Nigeria",
            "Nigeria",
            "https://hatscripts.github.io/circle-flags/flags/ng.svg"
        ),
        Country(
            "NI",
            "+505",
            "Nicaragua",
            "Nicaragua",
            "https://hatscripts.github.io/circle-flags/flags/ni.svg"
        ),
        Country(
            "NL",
            "+31",
            "Nederland",
            "Netherlands",
            "https://hatscripts.github.io/circle-flags/flags/nl.svg"
        ),
        Country(
            "NO",
            "+47",
            "Norge",
            "Norway",
            "https://hatscripts.github.io/circle-flags/flags/no.svg"
        ),
        Country(
            "NP",
            "+977",
            "नेपाल",
            "Nepal",
            "https://hatscripts.github.io/circle-flags/flags/np.svg"
        ),
        Country(
            "NZ",
            "+64",
            "New Zealand",
            "New Zealand",
            "https://hatscripts.github.io/circle-flags/flags/nz.svg"
        ),
        Country(
            "OM",
            "+968",
            "عُمان",
            "Oman",
            "https://hatscripts.github.io/circle-flags/flags/om.svg"
        ),
        Country(
            "PA",
            "+507",
            "Panamá",
            "Panama",
            "https://hatscripts.github.io/circle-flags/flags/pa.svg"
        ),
        Country(
            "PE",
            "+51",
            "Perú",
            "Peru",
            "https://hatscripts.github.io/circle-flags/flags/pe.svg"
        ),
        Country(
            "PH",
            "+63",
            "Pilipinas",
            "Philippines",
            "https://hatscripts.github.io/circle-flags/flags/ph.svg"
        ),
        Country(
            "PK",
            "+92",
            "پاکستان",
            "Pakistan",
            "https://hatscripts.github.io/circle-flags/flags/pk.svg"
        ),
        Country(
            "PL",
            "+48",
            "Polska",
            "Poland",
            "https://hatscripts.github.io/circle-flags/flags/pl.svg"
        ),
        Country(
            "PS",
            "+970",
            "فلسطين",
            "Palestine",
            "https://hatscripts.github.io/circle-flags/flags/ps.svg"
        ),
        Country(
            "PT",
            "+351",
            "Portugal",
            "Portugal",
            "https://hatscripts.github.io/circle-flags/flags/pt.svg"
        ),
        Country(
            "PY",
            "+595",
            "Paraguay",
            "Paraguay",
            "https://hatscripts.github.io/circle-flags/flags/py.svg"
        ),
        Country(
            "QA",
            "+974",
            "قطر",
            "Qatar",
            "https://hatscripts.github.io/circle-flags/flags/qa.svg"
        ),
        Country(
            "RO",
            "+40",
            "România",
            "Romania",
            "https://hatscripts.github.io/circle-flags/flags/ro.svg"
        ),
        Country(
            "RS",
            "+381",
            "Србија",
            "Serbia",
            "https://hatscripts.github.io/circle-flags/flags/rs.svg"
        ),
        Country(
            "RU",
            "+7",
            "Россия",
            "Russia",
            "https://hatscripts.github.io/circle-flags/flags/ru.svg"
        ),
        Country(
            "RW",
            "+250",
            "Rwanda",
            "Rwanda",
            "https://hatscripts.github.io/circle-flags/flags/rw.svg"
        ),
        Country(
            "SA",
            "+966",
            "المملكة العربية السعودية",
            "Saudi Arabia",
            "https://hatscripts.github.io/circle-flags/flags/sa.svg"
        ),
        Country(
            "SB",
            "+677",
            "Solomon Islands",
            "Solomon Islands",
            "https://hatscripts.github.io/circle-flags/flags/sb.svg"
        ),
        Country(
            "SC",
            "+248",
            "Seychelles",
            "Seychelles",
            "https://hatscripts.github.io/circle-flags/flags/sc.svg"
        ),
        Country(
            "SD",
            "+249",
            "السودان",
            "Sudan",
            "https://hatscripts.github.io/circle-flags/flags/sd.svg"
        ),
        Country(
            "SE",
            "+46",
            "Sverige",
            "Sweden",
            "https://hatscripts.github.io/circle-flags/flags/se.svg"
        ),
        Country(
            "SG",
            "+65",
            "Singapore",
            "Singapore",
            "https://hatscripts.github.io/circle-flags/flags/sg.svg"
        ),
        Country(
            "SI",
            "+386",
            "Slovenija",
            "Slovenia",
            "https://hatscripts.github.io/circle-flags/flags/si.svg"
        ),
        Country(
            "SK",
            "+421",
            "Slovensko",
            "Slovakia",
            "https://hatscripts.github.io/circle-flags/flags/sk.svg"
        ),
        Country(
            "SL",
            "+232",
            "Sierra Leone",
            "Sierra Leone",
            "https://hatscripts.github.io/circle-flags/flags/sl.svg"
        ),
        Country(
            "SM",
            "+378",
            "San Marino",
            "San Marino",
            "https://hatscripts.github.io/circle-flags/flags/sm.svg"
        ),
        Country(
            "SN",
            "+221",
            "Sénégal",
            "Senegal",
            "https://hatscripts.github.io/circle-flags/flags/sn.svg"
        ),
        Country(
            "SO",
            "+252",
            "Soomaaliya",
            "Somalia",
            "https://hatscripts.github.io/circle-flags/flags/so.svg"
        ),
        Country(
            "SR",
            "+597",
            "Suriname",
            "Suriname",
            "https://hatscripts.github.io/circle-flags/flags/sr.svg"
        ),
        Country(
            "SS",
            "+211",
            "South Sudan",
            "South Sudan",
            "https://hatscripts.github.io/circle-flags/flags/ss.svg"
        ),
        Country(
            "ST",
            "+239",
            "São Tomé e Príncipe",
            "São Tomé and Príncipe",
            "https://hatscripts.github.io/circle-flags/flags/st.svg"
        ),
        Country(
            "SV",
            "+503",
            "El Salvador",
            "El Salvador",
            "https://hatscripts.github.io/circle-flags/flags/sv.svg"
        ),
        Country(
            "SY",
            "+963",
            "سوريا",
            "Syria",
            "https://hatscripts.github.io/circle-flags/flags/sy.svg"
        ),
        Country(
            "SZ",
            "+268",
            "Eswatini",
            "Eswatini",
            "https://hatscripts.github.io/circle-flags/flags/sz.svg"
        ),
        Country(
            "TD",
            "+235",
            "Tchad",
            "Chad",
            "https://hatscripts.github.io/circle-flags/flags/td.svg"
        ),
        Country(
            "TG",
            "+228",
            "Togo",
            "Togo",
            "https://hatscripts.github.io/circle-flags/flags/tg.svg"
        ),
        Country(
            "TH",
            "+66",
            "ประเทศไทย",
            "Thailand",
            "https://hatscripts.github.io/circle-flags/flags/th.svg"
        ),
        Country(
            "TJ",
            "+992",
            "Тоҷикистон",
            "Tajikistan",
            "https://hatscripts.github.io/circle-flags/flags/tj.svg"
        ),
        Country(
            "TL",
            "+670",
            "Timor-Leste",
            "Timor-Leste",
            "https://hatscripts.github.io/circle-flags/flags/tl.svg"
        ),
        Country(
            "TM",
            "+993",
            "Türkmenistan",
            "Turkmenistan",
            "https://hatscripts.github.io/circle-flags/flags/tm.svg"
        ),
        Country(
            "TN",
            "+216",
            "تونس",
            "Tunisia",
            "https://hatscripts.github.io/circle-flags/flags/tn.svg"
        ),
        Country(
            "TO",
            "+676",
            "Tonga",
            "Tonga",
            "https://hatscripts.github.io/circle-flags/flags/to.svg"
        ),
        Country(
            "TR",
            "+90",
            "Türkiye",
            "Turkey",
            "https://hatscripts.github.io/circle-flags/flags/tr.svg"
        ),
        Country(
            "TT",
            "+1-868",
            "Trinidad and Tobago",
            "Trinidad and Tobago",
            "https://hatscripts.github.io/circle-flags/flags/tt.svg"
        ),
        Country(
            "TV",
            "+688",
            "Tuvalu",
            "Tuvalu",
            "https://hatscripts.github.io/circle-flags/flags/tv.svg"
        ),
        Country(
            "TZ",
            "+255",
            "Tanzania",
            "Tanzania",
            "https://hatscripts.github.io/circle-flags/flags/tz.svg"
        ),
        Country(
            "UA",
            "+380",
            "Україна",
            "Ukraine",
            "https://hatscripts.github.io/circle-flags/flags/ua.svg"
        ),
        Country(
            "UG",
            "+256",
            "Uganda",
            "Uganda",
            "https://hatscripts.github.io/circle-flags/flags/ug.svg"
        ),
        Country(
            "US",
            "+1",
            "United States",
            "United States",
            "https://hatscripts.github.io/circle-flags/flags/us.svg"
        ),
        Country(
            "UY",
            "+598",
            "Uruguay",
            "Uruguay",
            "https://hatscripts.github.io/circle-flags/flags/uy.svg"
        ),
        Country(
            "UZ",
            "+998",
            "Oʻzbekiston",
            "Uzbekistan",
            "https://hatscripts.github.io/circle-flags/flags/uz.svg"
        ),
        Country(
            "VA",
            "+379",
            "Vatican City",
            "Vatican City",
            "https://hatscripts.github.io/circle-flags/flags/va.svg"
        ),
        Country(
            "VE",
            "+58",
            "Venezuela",
            "Venezuela",
            "https://hatscripts.github.io/circle-flags/flags/ve.svg"
        ),
        Country(
            "VN",
            "+84",
            "Việt Nam",
            "Vietnam",
            "https://hatscripts.github.io/circle-flags/flags/vn.svg"
        ),
        Country(
            "VU",
            "+678",
            "Vanuatu",
            "Vanuatu",
            "https://hatscripts.github.io/circle-flags/flags/vu.svg"
        ),
        Country(
            "WS",
            "+685",
            "Samoa",
            "Samoa",
            "https://hatscripts.github.io/circle-flags/flags/ws.svg"
        ),
        Country(
            "YE",
            "+967",
            "اليمن",
            "Yemen",
            "https://hatscripts.github.io/circle-flags/flags/ye.svg"
        ),
        Country(
            "ZA",
            "+27",
            "South Africa",
            "South Africa",
            "https://hatscripts.github.io/circle-flags/flags/za.svg"
        ),
        Country(
            "ZM",
            "+260",
            "Zambia",
            "Zambia",
            "https://hatscripts.github.io/circle-flags/flags/zm.svg"
        ),
        Country(
            "ZW",
            "+263",
            "Zimbabwe",
            "Zimbabwe",
            "https://hatscripts.github.io/circle-flags/flags/zw.svg"
        )
    )
}





